# Generated by Django 5.0 on 2023-12-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income_expense", "0002_checkoutmodel_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type_name",
                    models.CharField(
                        choices=[
                            ("Income", "income"),
                            ("Expence", "expense"),
                            ("Income/Excome", "income/expense"),
                            ("Begin", "begin"),
                        ],
                        max_length=15,
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
