# Generated by Django 5.0 on 2023-12-29 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income_expense", "0006_alter_typeolddata_old_type_alter_types_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewActionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suma", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.CharField(max_length=120)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="from_user",
                        to="income_expense.checkoutmodel",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="to_user",
                        to="income_expense.checkoutmodel",
                    ),
                ),
                (
                    "type_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="income_expense.types",
                    ),
                ),
            ],
        ),
    ]
