# Generated by Django 5.0 on 2023-12-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income_expense", "0007_newactionmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newactionmodel",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
