# Generated by Django 5.0 on 2023-12-24 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telephone", models.CharField(max_length=15)),
                (
                    "town",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("VELINGRAD", "Velingrad"),
                            ("PLOVDIV", "Plovdiv"),
                            ("SOFIA", "Sofia"),
                            ("VARNA", "Varna"),
                        ],
                        default="UNKNOWN",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
